/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nrims.holder_ref_data;

import com.nrims.holder_data_mgmt.DataIO;
import com.nrims.holder_data_mgmt.DataPointFileProcessor;
import com.nrims.holder_data_mgmt.REFDataFile;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.io.File;
import java.util.HashSet;
import java.util.Set;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author fkashem
 */
public class Holder_Ref_Data_App extends javax.swing.JFrame {

    /**
     * Creates new form Holder_Ref_Data_App
     */
    public Holder_Ref_Data_App() {
        initComponents();
        initInternalData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        srcTableRightClick = new javax.swing.JPopupMenu();
        toggleRefPoint = new javax.swing.JMenuItem();
        generateButton = new javax.swing.JButton();
        testRun = new javax.swing.JButton();
        srcLabel = new javax.swing.JLabel();
        destLabel = new javax.swing.JLabel();
        destScrollPane = new javax.swing.JScrollPane();
        destReviewTable = new javax.swing.JTable();
        srcScrollPane = new javax.swing.JScrollPane();
        srcReviewTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusTextArea = new javax.swing.JTextArea();
        logLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        saveREFMenuItem = new javax.swing.JMenuItem();
        savePRSMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        setupMenu = new javax.swing.JMenu();
        loadCoords = new javax.swing.JMenuItem();
        loadCoeff = new javax.swing.JMenuItem();
        calcCoeffMenuItem = new javax.swing.JMenuItem();
        openREF = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        srcTableRightClick.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        srcTableRightClick.setInvoker(srcReviewTable);

        toggleRefPoint.setText("Toggle Reference Point");
        toggleRefPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleRefPointActionPerformed(evt);
            }
        });
        srcTableRightClick.add(toggleRefPoint);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Holder Reference Point Utility");

        generateButton.setText("Generate");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        testRun.setText("Testing");
        testRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testRunActionPerformed(evt);
            }
        });

        srcLabel.setText("Source Points");

        destLabel.setText("Destination Points");

        destReviewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        destScrollPane.setViewportView(destReviewTable);

        srcReviewTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                srcReviewTableMouseClicked(evt);
            }
        });
        srcScrollPane.setViewportView(srcReviewTable);

        statusTextArea.setColumns(20);
        statusTextArea.setRows(5);
        jScrollPane1.setViewportView(statusTextArea);

        logLabel.setText("Log: ");

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        saveREFMenuItem.setMnemonic('s');
        saveREFMenuItem.setText("Save .ref File");
        saveREFMenuItem.setEnabled(false);
        saveREFMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveREFMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveREFMenuItem);

        savePRSMenuItem.setMnemonic('a');
        savePRSMenuItem.setText("Save .prs FIle");
        savePRSMenuItem.setEnabled(false);
        savePRSMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePRSMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(savePRSMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setupMenu.setText("Setup");

        loadCoords.setText("Load Point Coords File");
        loadCoords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadCoordsActionPerformed(evt);
            }
        });
        setupMenu.add(loadCoords);

        loadCoeff.setText("Load Coefficient File");
        loadCoeff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadCoeffActionPerformed(evt);
            }
        });
        setupMenu.add(loadCoeff);

        calcCoeffMenuItem.setText("Calculate Coefficients");
        calcCoeffMenuItem.setEnabled(false);
        calcCoeffMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcCoeffMenuItemActionPerformed(evt);
            }
        });
        setupMenu.add(calcCoeffMenuItem);

        openREF.setText("Open .ref File");
        openREF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openREFActionPerformed(evt);
            }
        });
        setupMenu.add(openREF);

        menuBar.add(setupMenu);

        helpMenu.setText("Help");

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(srcScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(srcLabel)
                                .addGap(211, 211, 211)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(destLabel)
                            .addComponent(destScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(testRun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generateButton))
                            .addComponent(logLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testRun)
                    .addComponent(generateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srcLabel)
                    .addComponent(destLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(srcScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(destScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(logLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    /*
     * Save .ref file menu item action.
     */
    private void saveREFMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveREFMenuItemActionPerformed
        int returnVal = fc.showSaveDialog( this );
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            updateStatus(DataIO.saveREF(fc.getSelectedFile().getPath(), dpfp));
        }
    }//GEN-LAST:event_saveREFMenuItemActionPerformed

    private void savePRSMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePRSMenuItemActionPerformed
        int saveApprove = fc.showSaveDialog( this );
        if (saveApprove == JFileChooser.APPROVE_OPTION) {
            updateStatus(DataIO.savePRS(fc.getSelectedFile().getAbsolutePath(), dpfp));
        }
    }//GEN-LAST:event_savePRSMenuItemActionPerformed

    private void loadCoeffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadCoeffActionPerformed
        int returnVal = fc.showOpenDialog( this );
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            coeffFilePath = fc.getSelectedFile().getPath();
            dpfp.setCoeffFilePath(coeffFilePath);
            updateStatus("Coefficient file chosen.");
        }
    }//GEN-LAST:event_loadCoeffActionPerformed

    private void loadCoordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadCoordsActionPerformed
        int returnVal = fc.showOpenDialog( this );
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            coordFilePath = fc.getSelectedFile().getPath();
            dpfp.setScopeFilePath(coordFilePath);
            dpfp.clearMachinePoints();
            srcTableRefresh(TableCode.NIKON);
            destTableRefresh(TableCode.CLEAR);
            calcCoeffMenuItem.setEnabled(true);
            updateStatus("Coordinate file chosen.");
        }
        
    }//GEN-LAST:event_loadCoordsActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        dpfp.processTransform();
        
        /* This is to generate with the new comment rather than the default. 
         * Deal with this later
        for (int i=0; i<rpl.getNumRefPoints(); i++)
            rpl.getRefPoint(i).setComment(getCommentFor(i));
            * 
            */
        
        destTableRefresh(TableCode.REF);
        enableSaves(true);
        updateStatus("Points transformed.");
    }//GEN-LAST:event_generateButtonActionPerformed

    private void testRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testRunActionPerformed
        coeffFilePath = "/nrims/home3/fkashem/NetBeansProjects/nikon2mims/trunk/holder_ref_data/test/gwen-exp9/coeff-gwen-exp9.txt";
        coordFilePath = "/nrims/home3/fkashem/NetBeansProjects/nikon2mims/trunk/holder_ref_data/test/gwen-exp9/xy.points";
        dpfp.setScopeFilePath(coordFilePath);
        calcCoeffMenuItem.setEnabled(true);
        srcTableRefresh(TableCode.NIKON);
        dpfp.setCoeffFilePath(coeffFilePath);
        dpfp.processTransform();
        destTableRefresh(TableCode.REF);
        updateStatus("Test script ran.");
    }//GEN-LAST:event_testRunActionPerformed

    /*
     * Open .ref file and display in source table
     */
    private void openREFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openREFActionPerformed
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            DataIO.openREF(fc.getSelectedFile().getPath(), dpfp);
            srcTableRefresh(TableCode.REF);
            updateStatus("Opened .ref File");
        }
    }//GEN-LAST:event_openREFActionPerformed

    /*
     * Right click on rows in source table
     */
    private void srcReviewTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_srcReviewTableMouseClicked
        if(SwingUtilities.isRightMouseButton(evt)) {
            srcTableRightClick.show(srcReviewTable, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_srcReviewTableMouseClicked

    private void toggleRefPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleRefPointActionPerformed
        // TODO add your handling code here:
        // Get list of points selected -->  iterate through list, toggle isReference
        for (int i : srcReviewTable.getSelectedRows()) {
            boolean addRemove = dpfp.toggleReferenceFlag(i); 
            if(addRemove) {
                updateStatus("Point " + dpfp.getScopePoints().get(i).getNum() + ": reference point added.");
            } else {
                updateStatus("Point " + dpfp.getScopePoints().get(i).getNum() + ": reference point removed.");
            }
        }
        updateStatus(dpfp.getReferencePoints().size() + " reference points total.");
        srcTableRefresh(TableCode.NIKON);
    }//GEN-LAST:event_toggleRefPointActionPerformed

    private void calcCoeffMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcCoeffMenuItemActionPerformed
        if(calculateWindow != null) {
            calculateWindow.setData(dpfp);
        } else {
            calculateWindow = new CoeffCalcWindow(dpfp);
        }
        calculateWindow.setVisible(true);
    }//GEN-LAST:event_calcCoeffMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Holder_Ref_Data_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Holder_Ref_Data_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Holder_Ref_Data_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Holder_Ref_Data_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Holder_Ref_Data_App().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem calcCoeffMenuItem;
    private javax.swing.JLabel destLabel;
    private javax.swing.JTable destReviewTable;
    private javax.swing.JScrollPane destScrollPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton generateButton;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem loadCoeff;
    private javax.swing.JMenuItem loadCoords;
    private javax.swing.JLabel logLabel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openREF;
    private javax.swing.JMenuItem savePRSMenuItem;
    private javax.swing.JMenuItem saveREFMenuItem;
    private javax.swing.JMenu setupMenu;
    private javax.swing.JLabel srcLabel;
    private javax.swing.JTable srcReviewTable;
    private javax.swing.JScrollPane srcScrollPane;
    private javax.swing.JPopupMenu srcTableRightClick;
    private javax.swing.JTextArea statusTextArea;
    private javax.swing.JButton testRun;
    private javax.swing.JMenuItem toggleRefPoint;
    // End of variables declaration//GEN-END:variables

    /* custom private variables */
    private DataPointFileProcessor dpfp = new DataPointFileProcessor();
    private RDRTableModel refTableModel = new RDRTableModel(dpfp);
    private NikonTableModel nikonTableModel = new NikonTableModel(dpfp); 
    private JDialog aboutBox;
    private JFileChooser fc = new JFileChooser();
    private String coeffFilePath;
    private String coordFilePath;
    private String refFilePath;
    private CoeffCalcWindow calculateWindow;
    
    /* Codes for using the source tables. This is not the best way to do this. */
    private enum TableCode { REFRESH, NIKON, CLEAR, REF };
    
    public DataPointFileProcessor getData() {
        return dpfp;
    }
    
    private void initInternalData()
    {
       // data_point_comment_text.setText(
        //        dpfp.getRefPointList().getDefaultRefPointComment()
         //       );
        
       srcReviewTable.setDefaultRenderer(Object.class, new ReferenceTableRender());
       
    }
    
    /*
     * Refreshes destReviewTable with .ref points from dataPointFileProcessor
     */
    private void destTableRefresh(TableCode model) {
        switch(model) {
            case REF: 
                refTableModel.setDataPointFileProcessor(dpfp);
                destReviewTable.setModel(refTableModel);
                enableSaves(true);
            break;
            case CLEAR:
                destReviewTable.setModel(new RDRTableModel(new DataPointFileProcessor()));
                
                //This should go in a different method.
                enableSaves(false);
            break;
        }
    }
    
    /*
     * Refreshes source table with either nikon points or .ref points
     * Clear destination table every time the source table is reloaded
     * @param String modelType "nikon" or "ref" 
     */
    private void srcTableRefresh(TableCode model) {
        switch(model) {
            case REFRESH: 
                srcReviewTable.setModel(srcReviewTable.getModel());
            break;
            case NIKON: 
               nikonTableModel.setDataPointFileProcessor(dpfp);
               srcReviewTable.setModel(nikonTableModel);
               
               //Hide reference column in view if not hidden.
               if(srcReviewTable.getColumnModel().getColumnCount() > 4) {
                   srcReviewTable.removeColumn(srcReviewTable.getColumnModel().getColumn(4));
               }
            break;
            case REF:
                refTableModel.setDataPointFileProcessor(dpfp);
                srcReviewTable.setModel(refTableModel);
                
                //This should go in a different method.
                enableSaves(true);
            break;
        }
       
    }
    
    /*
     * Prints a string to the status log text area.
     * @param String to be printed
     */
    private void updateStatus(String line) {
        statusTextArea.append(line + "\n");
    }
    
    /* 
     * Enable/disable saving. Saving is enabled when there is a .ref or .prs file opened
     * and displayed in either the source or destination table.
     */
    private void enableSaves(boolean set) {
        savePRSMenuItem.setEnabled(set);
        saveREFMenuItem.setEnabled(set);
    }
}